theme: jekyll-theme-minimal
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: Nikolaos Margaris' CV
show_downloads: "true"
docs:
  pdf_url: "docs/CV - Nikolaos Margaris - 2020.pdf"
  doc_url: "docs/CV - Nikolaos Margaris - 2020.doc"
  odt_url: "docs/CV - Nikolaos Margaris - 2020.odt"